name: CI
on: [push]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2

      - run: npm i --legacy-peer-deps
      #- run: npx nx affected:test --verbose
      - run: npx nx affected:build --prod --verbose
      - run: npx nx affected:e2e --verbose
